### ISSUE TITLE
Add MLPACK to comparisons?

### ISSUE THREAD

**Issue by jjallaire** [szilard/benchm-ml#31]
Have you considered adding MLPACK to these comparisons: http://www.mlpack.org/

In these comparisons you can see it outperforming matlab, scikit, and weka on several benchmarks: http://www.mlpack.org/benchmarks.html

Note that there is already an RcppMLPACK package: https://cran.r-project.org/web/packages/RcppMLPACK/index.html

This provides the C++ interface. It would certainly also be interesting to provide an R interface if it's practical.

**Comment by szilard** [comment]
Thanks JJ for reaching out. I took a look at MLPACK's docs just now though I've seen the website and their benchmarks before.

The scope of my project is this: I wanted to see with _minimal work_ which **widely used** _open source_ tools can do **binary classification** on _10M records_. "Can do" means here **decent predictive accuracy**, decent _training time_ and not crashing out of memory on a box with lots of **RAM** (main points alternating in italic/bold).

Binary classification is probably the most common ML application. From informal surveys at meetups etc. it turns out ~80% of people doing non-linear supervised learning have datasets <10M records (that's not raw datasets, but after munging/cleaning/... and ready for modeling). 

The most widely used ML tools from informal [surveys](https://github.com/szilard/survey-ml-tools) and reading Kaggle forums etc. are R packages, Python sklearn, VW, H2O, xgboost. I also added Spark MLlib because of the hype, but it clearly disappoints in many aspects.

It is known in the [literature](https://www.cs.cornell.edu/~caruana/ctp/ct.papers/caruana.icml06.pdf) that the most accurate algos are random forests, gradient boosted machines, neural networks (possibly deep NN) and (non-linear) support vector machines. This is also my experience with trying these and many others over the years, and they are also the algos that are used for winning Kaggle competitions. (Non-linear) SVM's computational needs are > O(N) and can't scale to 10M records, therefore I focus on RF, GBM, NN. I also added logistic regression as a baseline. LR and in general linear models are useful on very large and high-dimensionality data when the other models might break. There is no need to look at naive Bayes, k-nearest neighbors, simple decision trees, bagged trees and many other methods as they are almost never in the top as accuracy.

Now to MLPACK: I don't think it's widely used. It has many unsupervised learning algos, but for supervised it implements k-NN, linear models, naive Bayes etc. but none of the top accuracy models RF/GBM/NN. It does not interface super-easily with R and/or Python for now (yes, there is RcppMLPACK and surely one could write an R wrapper). (The 2 best tools from the above ones, H2O and xgboost have both nice R and Python interfaces). It seems at current stage MLPACK is single thread (with plans for multithreading). While multithreading is overkill for data munging (data.table or dplyr stuff) and most things people do in R, non-linear ML is very CPU intensive and you get a lot of benefit e.g. in xgboost/H2O from parallelizing on multicores. 

Finally, going back to the beginning of this reply about the scope of this benchmark to be achieved with minimal work, there are so many ML tools out there that it would be a lot of time for me to try them all. However, if someone wants to do it I'll be happy to post the results. I even created this [page](https://github.com/szilard/benchm-ml/tree/master/z-other-tools) for non-open source ML vendors to benchmark their tools (which I'm not gonna do) and report results if they want to (of course there will be a selection bias and also an issue of trust as I'm not verifying the results). 

 Even for the things I've done, I'm aware benchmarking is hard and I met people saying that's close to impossible to do it right, but I would think that comparing the most common use case with most common algos on most common tools etc. is valuable and it's really disappointing there are no benchmarks out there and people are choosing tools based mostly on hype and without trying multiple tools and deciding based on data.

**Comment by jjallaire** [comment]
Okay, that makes perfect sense. I agree that there is effectively no
interface from Python or R available. One issue they have is that
parameters to algorithms are specified as templates so in order to create
an R or Python interface you'd have to compile all of the permutations
ahead of time.

I was wondering about existing C++ ML libraries that we could create a nice
interface to from R. Another one on my list to check out was DLib (which
appears to be somewhat easier to wrap than MLPACK). Have you seen DLib and
might it be worth wrapping with a nice R interface? (http://dlib.net/ml.html
)

**Comment by szilard** [comment]
I see. I'm not familiar with DLib, but I'll take a look (and will reply you).

Also, my guess is that your broader goal is "how can we make R (even) better for machine learning?" Let me think about that too :)

**Comment by jjallaire** [comment]
Yes, that is the broader goal indeed! :-)

I'd also guess that helping authors of existing packages make their
implementations faster would be a big win.
